- name: Install Java
  become: yes
  hosts: all
  tasks:
    - name: Install Java in a cross-platform way
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
  vars:
    java_package: "{{ 'java-11-openjdk-devel' if ansible_distribution in ['CentOS','RedHat','Rocky'] else 'openjdk-11-jdk' }}"

